config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :stars, only: [:index, :show] do
    resources :bookings, only: [:create]
  end

  namespace :host do
    resources :stars, only: [:new, :create]

<<<<<<< HEAD
<<<<<<< HEAD
    resources :bookings, only: [:index] do
=======
    resources :bookings, only: [] do
>>>>>>> bc8ba21371eb804f0a6a211195fb3bfbd220cc39
=======
    resources :bookings, only: [:index] do

>>>>>>> a78e85eaddb75bde6715cd7844bd8f28873b99f7
      member do
        patch :accept
        patch :decline
      end
    end

  end

  resource :dashboard, only: :show
end
  # Defines the root path route ("/")
  # root "articles#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :star

  validates :status, inclusion: { in: ["accepted", "declined", "pending"] }
end

app/models/star.rb
class Star < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :stars
  has_many :bookings
  
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @star = Star.find(params[:star_id])
    @booking.user = current_user
    @booking.status = "pending"
    @booking.star = @star

    if @booking.save
      redirect_to dashboard_path(@booking)
    else
      render 'stars/show', status: :unprocessable_entity
    end
  end


  private

  def booking_params
    params.require(:booking).permit(:arrival_date, :departure_date)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @bookings = Booking.where(user: current_user)
    @stars = Star.where(user: current_user)
    @books_stars = Booking.includes(:star).where(star: { user: current_user })
    @user = current_user
  end

  private

  def dashboard_params
    params.require(:booking).permit(:status, :user_id, :star_id, :arrival_date, :departure_date, :total_price)
  end
end

app/controllers/host/bookings_controller.rb
class Host::BookingsController < ApplicationController
  # skip_before_action :authenticate_user!, only: %i[index accept decline]
  def accept
    @booking = Booking.find(params[:id])
    @booking.update(status: "accepted")
    redirect_to dashboard_path

  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.update(status: "declined")
    redirect_to dashboard_path
  end
end

app/controllers/host/stars_controller.rb
class Host::StarsController < ApplicationController
    skip_before_action :authenticate_user!, only: %i[index show]

    def new
        @star = Star.new
    end

    def create
      @star = Star.new(star_params)
      @star.user = current_user

      if @star.save!
        redirect_to dashboard_path
      else
        render "new", status: :unprocessable_entity
      end
    end

    def destroy
        @star.destroy
        redirect_to dashboard_path
    end

    private

    def star_params
        params.require(:star).permit(:name, :location, :climate, :capacity, :price_per_night, :user_id, :created_at, :updated_at)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home]

  def home
  end
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

    def index
      @stars = Star.all
    end

  def show
    @star = Star.find(params[:id])
    @booking = Booking.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Booking create</h1>

app/views/dashboards/show.html.erb
<%= render "shared/navbar" %>

  <div class = "container_dash">
  <h4 class="button_etoile_dash"><%= link_to "create your etoile",  new_host_star_path %></h4>
    <div class="title_dashboard">


  <h1>Mon dashboard</h1>
<%# si size booking = 1 donc element au milieu avec grid, grid area %>
  </div>
    </div>
      <h5><div class="card-header" >My booking </h5></div>
      <div class= "grid-dash">

        <% @bookings.each do |element|%>
        <div class="card">
        <div class="card-image"><%= cl_image_tag element.star.photo.key %> </div>
          <div class="card-description">
            <div>
              <div class = "booking_star_dispo  etir_margin" ><strong> <%= element.star.name %></strong>
              <%= element.total_price%></div>
              <div class = "booking_star_dispo">
              <div class = "retir_margin"> <strong><%= element.status %> </strong></div>
                <div><%= element.arrival_date %> </div>
                <div></div><%= element.departure_date %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>

    <h5><div class="card-header margin-head" >My stars </h5></div>

    <div class= "grid-dash">
      <% @stars.each do |detail| %>
      <div class="card">
        <div class = "rassemblement" >
          <div class="card-image">
            <% if detail.photo.present? %>
              <%= cl_image_tag detail.photo.key %>
            <% end %>
          </div>
          <div class="card-description">
            <div class = "booking_star_dispo">
              <div><strong><%= detail.name %></strong></div>
              <div><%= detail.price_per_night%> </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>



  <h5><div class="card-header margin-head" >My star booked </h5></div>
  <div class= "grid-dash">
    <% @books_stars.each do |booking| %>
      <div class="card">
        <div class="card-image"><%= cl_image_tag booking.star.photo.key %></div>
          <div class="card-description">
            <div class = "booking_star_dispo">
              <div><strong> <%= booking.star.name %></strong></div>
              <div><%= booking.status %> </div>
              <div> <%= booking.total_price%></div>
            </div>
                <div class = "button-dach-accep" >
                  <%= link_to "accept", accept_host_booking_path(booking) , data: { turbo_method: :patch },class: "link" %>
                  <%= link_to "decline", decline_host_booking_path(booking) , data: { turbo_method: :patch },class: "link"%>
                </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>



</div>
<%= render "shared/footer" %>

app/views/host/bookings/index.html.erb
<h1> Accepted booking </h1>




<div></div><form user="/controller/bookings" class="button_to">
    <input name="authenticity_token" type="hidden" value="10f2163b45388899ad4d5ae948988266befcb6c3d1b2451cf657a0c293d605a6" autocomplete="off"/>
</form>
  <%= button_to "Accept", accept_host_booking_path(@booking), method: :patch %>
  <%= button_to "Decline", decline_host_booking_path(@booking), method: :patch %>

  <% @bookings.each do |booking| %>
  <div class="card">
  <%= @star_books.status %>
  <%= booking.arrival_date %>

  </div>
<% end %>

app/views/host/stars/new.html.erb
<div class="container py-5">
    <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
    <h1>Be like a <strong>GOD</strong>, create a <strong>star</strong></h1>
        <div class="bg-white rounded p-3 shadow">

        <h3>Create a new star</h3>

        <%= simple_form_for [:host, @star] do |f| %>
            <%= f.input :name, placeholder: 'Name of your star here' %>
            <%= f.input :location, placeholder: 'Where is your star ?' %>
            <%= f.input :capacity, placeholder: 'How many people maximum ?' %>
            <%= f.input :climate, placeholder: 'What can I put in wallet ?' %>
            <%= f.input :price_per_night, placeholder: 'How much do you want to get?' %>
            <%= f.input :picture, as: :file %>
            <%= f.submit class: 'btn btn-primary' %>
        <% end %>
        </div>
    </div>
    </div>
</div>

<%= link_to 'Back', dashboard_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dream</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="position-relative pb-5" style="min-height:100vh">
    <%# <%= render "shared/navbar" %>
    <%= yield %>
    <%# <%= render "shared/footer" %>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/home.html.erb
<%# <a href="https://icons8.com/icon/y1bo9DEFx7BS/stars">Stars icon by Icons8</a> %>
<div class = "background_image_nova">
  <div class = "ta_mere">
    <h1 id="titre_homepage">Dream on Stars</h1>
    <div id = "phrase_daccroche">
      <h3 class="sous_titre_homepage">pourquoi se contenter de la lune?</h3>
      <h3 class="sous_titre_homepage">quand on peut viser les étoiles</h3>
      <h4 class="button_etoile"><%= link_to "Voir les étoiles", stars_path %></h4>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>

  <div class="main"></div>

  <div class="footer-text"> Copyright © Le Wagon ltd 2022 🚋 </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "logo_dream.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        <div class = "nav-link user-session">
        <% @user = current_user %>
        <%= @user.last_name %>
            <%= @user.first_name %>
        </div>
          <li class="nav-item active">
            <%= link_to "Home", root_path , class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Menu", stars_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "Futuramaprof.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Menu",stars_path, class: "dropdown-item" %>
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Se deconecter",destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete}, class: "dropdown-item"%>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/stars/index.html.erb
<%= render "shared/navbar" %>
<p id="notice"><%= notice %></p>

<h1 id="index_h1">Stars</h1>

<div class="cards-container">
  <% @stars.each do |star| %>
    <%= link_to  star_path(star) do %>
      <div class="card" >

        <div class="card-image"><%= cl_image_tag star.photo.key %></div>
        <div class="card-description">
        <div id= "card-name">
          <strong><%=  star.name %></strong>
          <p><strong><%= star.price_per_night %> </strong></p>
        </div>
          <p><%= star.location %></p>
        <%# <%= star.capacity %>
        <%# <%= star.climate.downcase %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<%= render "shared/footer" %>

app/views/stars/new.html.erb
<div class="container py-5">
    <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
    <h1>Be like a <strong>GOD</strong>, create a <strong>star</strong></h1>
        <div class="bg-white rounded p-3 shadow">

        <h3>Create a new star</h3>

        <%= simple_form_for @star do |f| %>
            <%= f.input :name, placeholder: 'Name of your star here' %>
            <%= f.input :location, placeholder: 'Where is your star ?' %>
            <%= f.input :capacity, placeholder: 'How many people maximum ?' %>
            <%= f.input :climate, placeholder: 'what can I pu in wallet' %>
            <%= f.input :price_per_night, placeholder: 'How much do you want to get?' %>
            <%= f.input :photo, as: :file %>
            <%= f.submit class: 'btn btn-flat' %>

            
        <% end %>
        </div>
    </div>
    </div>
</div>

<%= link_to 'Show', @stars %>
<%= link_to 'Back', dashboard_path %>

app/views/stars/show.html.erb
<%= render "shared/navbar"%>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-7">
      <%= cl_image_tag @star.photo.key, height: 474, width: 750,crop: :fill %>
        <div class="flexbox">
          <%# name %>
          <div class="name">
            <h1><%= @star.name%>💫</h1>
          </div>
          <%# climate %>
          <div class="climate">
            <h1> <%= @star.climate%>🌡</h1>
          </div>
          <%# capacity %>
          <div class="capacity">
            <h1>👨‍👨‍👧‍👦<%= @star.capacity%></h1>
          </div>
          <%# pricepernight %>
          <div class="ppn">
            <h1> <%= @star.price_per_night%></h1>
          </div>
        </div>
    </div>

        <div class="col-12 col-lg-5">
        <%# nombre de personnes %>
        <div class="calendar">
          <div class="host">
            <p>🔑Processus d'arrivée <strong>fantastique.</strong></p>
            <p>✈️100 % de voyageurs récents ont attribué 5 🌟🌟🌟🌟🌟 au processus d'enregistrement.</p>

            <p>👩🏼‍🚀👨🏽‍🚀Le propietaire de <strong><%= @star.name%></strong> est un <strong>Superhost.</strong>
            <p>🥇Les 🦸🏼Superhosts🦸🏻‍♀️ sont des hôtes expérimentés très bien notés qui font tout leur
            possible pour offrir aux clients des séjours inoubliables🤩.</p>
            <p>📆Annulation <strong>gratuite</strong> 48 heures avant la date de reservation.</p>

          </div>

            <div class="reservation">

              <%= simple_form_for [@star, @booking] do |f| %>
                  <%= f.input :departure_date, html5: true %>
                  <%= f.input :arrival_date, html5: true %>
                  <%= f.submit "Reservez un sejour inoubliable", class: "button"  %>
                <% end %>




          </div>
        </div>




        </div>
      <!-- This div is centered and takes 6 columns -->
    </div>
  </div>
</div>
<%= render "shared/footer" %>